# Generated by Django 5.0.3 on 2024-03-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='units', max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(through='inventory.RecipeRequirement', to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='inventory.menuitem'),
        ),
    ]
