# Generated by Django 5.0.3 on 2024-04-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='available_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('l', 'liter'), ('cup', 'cup'), ('oz', 'ounces'), ('lbs', 'pound'), ('', '')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('l', 'liter'), ('cup', 'cup'), ('oz', 'ounces'), ('lbs', 'pound'), ('', '')], default='', max_length=200),
        ),
    ]
