# Generated by Django 5.0.3 on 2024-04-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='unit',
        ),
    ]
