# Generated by Django 5.0.3 on 2024-05-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_menuitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
    ]
