# Generated by Django 5.0.3 on 2024-05-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_reciperequirement_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='price_per_unit',
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('l', 'liter'), ('cup', 'cup'), ('oz', 'ounces'), ('lbs', 'pound'), ('', '')], default='', max_length=10),
        ),
    ]
