# Generated by Django 5.0.3 on 2024-05-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_reciperequirement_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('l', 'liter'), ('cup', 'cup'), ('oz', 'ounces'), ('lbs', 'pound'), ('', '')], default='', max_length=200),
        ),
    ]
